name: Update Credentials via Dispatch

on:
  repository_dispatch:
    types: [update-credentials]

permissions:
  contents: write
  repository_dispatch: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update credentials.txt
        run: |
          echo "username:${{ github.event.client_payload.username }}" > credentials.txt
          echo "password:${{ github.event.client_payload.password }}" >> credentials.txt
          echo "credit:${{ github.event.client_payload.credit }}" >> credentials.txt
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add credentials.txt
          git commit -m "Update credentials"
          git push
