name: Update Credentials via Dispatch

on:
  repository_dispatch:
    types:
      - update-credentials

permissions:
  contents: write
  repository-projects: write

jobs:
  update-credentials:
    runs-on: ubuntu-latest
    env:
      # هذا يجلب SECRET من Settings → Secrets into an env var
      DISPATCH_SECRET: ${{ secrets.DISPATCH_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate dispatch secret
        run: |
          if [ "${{ github.event.client_payload.secret }}" != "$DISPATCH_SECRET" ]; then
            echo "❌ Invalid dispatch secret, aborting."
            exit 1
          fi

      - name: Update credentials.txt
        run: |
          echo "username:${{ github.event.client_payload.username }}" > credentials.txt
          echo "password:${{ github.event.client_payload.password }}" >> credentials.txt
          echo "credit:${{ github.event.client_payload.credit }}" >> credentials.txt

          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add credentials.txt
          git diff --cached --quiet || git commit -m "Update credentials"
          git push
